### ISSUE TITLE
x-forwarded-proto not being set when using http 

### ISSUE THREAD

**Issue by owenhaynes** [zlabjp/nghttpx-ingress-lb#42]
Using ELB Loadbalancer to terminate https. x-forwarded-proto is set to https but this is not passed through nghttpx replaces it to http

**Comment by tatsuhiro-t** [comment]
Confirmed.  This is nghttpx bug.

**Comment by tatsuhiro-t** [comment]
`no-strip-incoming-x-forwarded-proto=yes` tells nghttpx not to strip the incoming X-Forwarded-Proto header field.
See https://github.com/zlabjp/nghttpx-ingress-lb#custom-nghttpx-configuration
