### ISSUE TITLE
echoheaders example on Google Container Engine

### ISSUE THREAD

**Issue by markbarks** [zlabjp/nghttpx-ingress-lb#52]
Hi,
I've been trying and failing to get the echoheaders example to work on Google Container Engine. I'm at a bit of a loss to explain why - the controller allocates a public IP to the ingress, but when I run curl it just times out. I've run the example on minikube successfully.

I've added the kubernetes.io/ingress.class: "nghttpx" annotation to the pod spec, to prevent conflicts with the glbc controller (it was flipping ip before I did this).

I've attached the log from the controller - I'd be really grateful if someone could take a look and see if something is going wrong there. Controller deployment spec is also attached.

One other question - does nghttpx support ssl passthrough (http2)? I want to terminate ssl in Google Cloud Endpoints.

[ingress-gke.txt](https://github.com/zlabjp/nghttpx-ingress-lb/files/1050604/ingress-gke.txt)

[rc-default.yaml.txt](https://github.com/zlabjp/nghttpx-ingress-lb/files/1050606/rc-default.yaml.txt)

Thanks

**Comment by tatsuhiro-t** [comment]
From ingress-gke.txt, ingress controller successfully created configurations, and reloaded nghttpx.
The log does not include any access from curl, so I think that the packet didn't reached to nghttpx.
I'll check that ingress controller sets correct IP address to Ingress resource. Meanwhile, current Deployment uses hostNetwork to avoid CNI issue, and I've not used GKE before, and not sure it works there.

TLS termination works.  The thing is that nghttpx does forwarding on L7, not L4.

**Comment by markbarks** [comment]
> TLS termination works. The thing is that nghttpx does forwarding on L7, not L4.

Ah yes indeed. I didn't think it through properly. I'll close this.
