### ISSUE TITLE
Add PROXY protol support for frontend servers

### ISSUE THREAD

**Issue by weitzj** [zlabjp/nghttpx-ingress-lb#59]
In case you are running nghttpx-ingress-lb behind a LoadBalancer you might
to preserve the ClientIP addresses accessing your Kubernetes cluster.

As an example we are using a deployment on a Kubernetes on AWS.

In order to use all nghttpx features, especially upstream HTTP/2 forwarding
and TLS SNI, the only way to deploy nghttpx-ingress-lb, is to use an
AWS ELB (Classic LoadBalancer) in TCP mode and let nghttpx do the
TLS-termination, because:

- AWS ELB does not handle HTTP/2 at all.
- AWS ALB does not handle upstream HTTP/2 (http://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-listeners.html)
> Application Load Balancers provide native support for HTTP/2 with HTTPS listeners. You can send up to 128 requests in parallel using one HTTP/2 connection. The load balancer converts these to individual HTTP/1.1 requests and distributes them across the healthy targets in the target group using the round robin routing algorithm. Because HTTP/2 uses front-end connections more efficiently, you might notice fewer connections between clients and the load balancer. Note that you can't use the server-push feature of HTTP/2.

Therefore using an `X-Forward-For` header does not work, and you have to rely
on the PROXY-protocol feature.

This can be enabled via https://nghttp2.org/documentation/nghttpx-howto.html#enable-proxy-protocol

**Comment by weitzj** [comment]
@tatsuhiro-t

**Comment by tatsuhiro-t** [comment]
Thank you.  Will review PR.
