### ISSUE TITLE
ingress for grpc service

### ISSUE THREAD

**Issue by arunkjn** [zlabjp/nghttpx-ingress-lb#61]
Hi,

I was able to use this as an ingress controller for my grpc service. It handles tls termination correctly but my rpc subscription which is an indefinite stream disconnect after sometime with the following message on the client-

```
WARNING: RPC failed: Status{code=INTERNAL, description=Connection closed with unknown cause, cause=null}
```

Any idea what might be causing this? Do I need to configure something?

**Comment by tatsuhiro-t** [comment]
https://github.com/nghttp2/nghttp2/issues/1017

**Comment by arunkjn** [comment]
i will close this issue here
