### ISSUE TITLE
pls add ingress.zlab.co.jp/default-backend-config

### ISSUE THREAD

**Issue by arief-hidayat** [zlabjp/nghttpx-ingress-lb#63]
Currently, default backend config is hardcoded, to use http/1.1.

Imagine if I have hundreds of services with proto h2.
It would be great to have ingress.zlab.co.jp/default-backend-config so that I don't need to keep appending entries in ingress.zlab.co.jp/backend-config.

**Comment by tatsuhiro-t** [comment]
It sounds like a good idea.
I'd like to confirm that your idea is add new annotation "ingress.zlab.co.jp/default-backend-config" to Ingress resource, and it specifies the configuration which applies to all entries in the same Ingress.

**Comment by arief-hidayat** [comment]
yes. that's the idea.

**Comment by tatsuhiro-t** [comment]
#64 implements "ingress.zlab.co.jp/default-backend-config."

**Comment by arief-hidayat** [comment]
great. thx
