### ISSUE TITLE
request to add publish-service flag

### ISSUE THREAD

**Issue by arief-hidayat** [zlabjp/nghttpx-ingress-lb#65]
From your implementation (v0.26.0), I see ingress loadbalancer IP is updated with value from pods' cluster IP.
Somehow, this doesn't work with our dev cluster setup. My pod doesn't have this cluster IP.

I still don't understand the whole concept of how the ingress ( status -> loadBalancer  -> ingress-> ip/hostname) is used. 
But, I tried to modify the code to do similar thing like I found in ingress-nginx setup, which is setting 
the loadbalancer hostname from the publish-service , which is an AWS ELB in my case.
And somehow, my setup works with this change.

Can we have same 'publish-service' flag in nghttpx ingress?

https://github.com/kubernetes/ingress-nginx/blob/master/cmd/nginx/flags.go

```
publishSvc = flags.String("publish-service", "",
			`Service fronting the ingress controllers. Takes the form namespace/name. 
The controller will set the endpoint records on the ingress objects to reflect those on the service.`)
```

Thanks

**Comment by tatsuhiro-t** [comment]
Will do.

**Comment by arief-hidayat** [comment]
wow. thank you. looking forward to the next release

**Comment by arief-hidayat** [comment]
when do you plan to have the next release? thx

**Comment by tatsuhiro-t** [comment]
Late in this month.
