### ISSUE TITLE
redirect-if-not-tls in backend template 

### ISSUE THREAD

**Issue by arief-hidayat** [zlabjp/nghttpx-ingress-lb#67]
Regarding https://github.com/zlabjp/nghttpx-ingress-lb/blob/master/nghttpx-backend.tmpl,

would it be more correct to have this condition?

```
{{ if and $upstream.RedirectIfNotTLS $backend.TLS }};redirect-if-not-tls{{ end}}
```

If I set 'no-tls' for my backend service, it should not redirect to tls, even if there's SSL secret in the ingress setup.

CMIIW

**Comment by tatsuhiro-t** [comment]
I think $upstream.RedirectIfNotTLS is nothing to do with whether backend uses TLS or not.
$upstream.RedirectIfNotTLS is related to frontend TLS connection, not backend connection.
That said, I might be missing something.

Re-reading README, the following sentence might be misleading:

> If TLS is configured for a service, and it is accessed via cleartext HTTP, those requests are redirected to https URI.

"TLS is configured for a service" means that TLS certificate is set in Ingress resource, and does not mean TLS connection is used between ingress load balancer, and Pods.

**Comment by arief-hidayat** [comment]
i think you are right. let's close this then. thx
