### ISSUE TITLE
backendconfig API endpoint returned unsuccessful status code 413

### ISSUE THREAD

**Issue by arief-hidayat** [zlabjp/nghttpx-ingress-lb#69]
I tried to add more ingresses and I got the following
```
I1130 07:57:22.531942       1 command.go:139] Issuing API request http://127.0.0.1:10902/api/v1beta1/backendconfig
127.0.0.1 - - [30/Nov/2017:07:57:22 +0000] "POST /api/v1beta1/backendconfig HTTP/1.1" 413 31 "-" "Go-http-client/1.1"
E1130 07:57:22.532430       1 controller.go:686] failed to issue backend replace request: backendconfig API endpoint returned unsuccessful status code 413
```

what's the limit of the entries we can put nghttpx-backend.conf?
is it possible to increase it?

**Comment by tatsuhiro-t** [comment]
16KiB by default.
It can be configured using --api-max-request-body:

```
  --api-max-request-body=<SIZE>
              Set the maximum size of request body for API request.
              Default: 16K
```

**Comment by arief-hidayat** [comment]
thanks.
any recommendation on max value that we can set there? e.g. 1M?
so, that when my config file size is reaching that size, perhaps it is better setup a new ingress controller

**Comment by tatsuhiro-t** [comment]
The current implementation keeps all requests in memory.   As long as it can allocate the memory, it is fine.  I think 1M is OK.  FYI, you can check the actual size of file in nghttpx-ingress-controller pod; its path is /etc/nghttpx/nghttpx-backend.conf

**Comment by arief-hidayat** [comment]
thanks

**Comment by tatsuhiro-t** [comment]
I will increase the default size limit in the next nghttp2 release.  I think 16KiB is too small.
