### ISSUE TITLE
is it possible to watch several k8s namespaces?

### ISSUE THREAD

**Issue by arief-hidayat** [zlabjp/nghttpx-ingress-lb#79]
can we specify several namespaces in `watch-namespace` ?
e.g. watch-namespace=default,dev01,dev02

thanks

**Comment by tatsuhiro-t** [comment]
Will see that it is possible.

**Comment by tatsuhiro-t** [comment]
If your use case is partition Ingress resources into multiple Ingress controllers, Ingress class annotation is handy.  See https://github.com/zlabjp/nghttpx-ingress-lb#ingress-class

**Comment by arief-hidayat** [comment]
Thanks. I'll consider that option.
