### ISSUE TITLE
how to debug the routing process

### ISSUE THREAD

**Issue by arief-hidayat** [zlabjp/nghttpx-ingress-lb#80]
Hi, 

I have issue where valid request is routed 404 instead of routed to the corresponding pod.
I can see the pod routing in /etc/nghttpx/nghttpx-backend.conf.

I can see from access log
"POST /tensorflow.serving.PredictionService/Predict HTTP/2" 404 21 "-" "grpc-python/1.4.0 grpc-c/4.0.0 (windows; chttp2; gregarious)"

Do you have tips on how to further debug? any particular log pattern I can search to find out why it went to 404?

Thanks

**Comment by tatsuhiro-t** [comment]
nghttpx logs routing info in its error.log when the log level is INFO.  First run nghttpx with --log-level=INFO.  For ingress controller, use ConfigMap, and write `log-level=INFO` there.  error.log is redirected to stderr by default.

On startup, nghttpx logs routing configuration:

```
INFO (shrpx_config.cc:3793) Host-path pattern: group 0: '/foo'
INFO (shrpx_config.cc:3796) group 0 -> 127.0.0.1:80, proto=http/1.1
INFO (shrpx_config.cc:3793) Host-path pattern: group 1: '/'
INFO (shrpx_config.cc:3796) group 1 -> 127.0.0.1:80, proto=http/1.1
INFO (shrpx_config.cc:3812) Catch-all pattern is group 1
```

In this case, there is 2 patterns; "/foo", and "/".

For each request, nghttpx logs the result of pattern match:

```
INFO (shrpx_worker.cc:523) Perform mapping selection, using host=localhost, path=/foo
INFO (shrpx_worker.cc:578) Found pattern with query /foo, matched pattern=/foo
```

**Comment by arief-hidayat** [comment]
Thanks for the reply.

I could not found those "Perform mapping selection" or "Found pattern" in my kibana (which probably only the error message.
There are log INFO from kubernetes dashboard. However, I could not find such logs

Perhaps I should add `-stderrthreshold=INFO` to make all INFO logs to stderr, hence it will be displayed in kibana. Am I right?

**Comment by tatsuhiro-t** [comment]
-stderrthreshold controls glog.  The log from nghttpx process is directly written to stderr, which means the log from ingress controller, and nghttpx process are somewhat interleaved.
I think the log level of nghttpx is not set to INFO.  Setting log level of glog to INFO does not achieve it.
Here is an example how to set nghttpx's log level to INFO: https://github.com/zlabjp/nghttpx-ingress-lb#custom-nghttpx-configuration

**Comment by arief-hidayat** [comment]
I've set the log level to INFO. in my configMap
```
add-x-forwarded-for=yes
strip-incoming-x-forwarded-for=yes
log-level=INFO
accesslog-file=/usr/local/nghttpx-access.log
backend-write-timeout=15m
backend-read-timeout=15m
frontend-write-timeout=15m
frontend-read-timeout=15m
frontend-http2-read-timeout=15m
```

I can find "shrpx_worker.cc" from kubernetes dashboard UI. the pod's log.
```
2018-01-30T01:27:20.986Z 15 25 5eecac9a INFO (shrpx_worker.cc:371) [WORKER:0x7f7149557000] WorkerEvent: client_fd=32, addrlen=16
2018-01-30T01:27:20.986Z 15 25 5eecac9a INFO (shrpx_worker.cc:398) [WORKER:0x7f7149557000] CLIENT_HANDLER:0x7f714601b800 created 
```

In kibana, searching "shrpx_worker.cc" will only give me the following log pattern
NOTICE (shrpx_worker.cc:411) [WORKER:0x7f3a2392f000] Graceful shutdown commencing

**Comment by tatsuhiro-t** [comment]
At least one request should be sent to nghttpx to get the log message.

**Comment by arief-hidayat** [comment]
of course, there are requests coming in.  I am sending request as well as tailing the access log as well.
I'm using v0.28.0 btw. should I upgrade to v0.29.1?

**Comment by tatsuhiro-t** [comment]
v0.28.0 is high enough to see these log messages.
It is strange that you cannot see them.  I can read them from pod log.

**Comment by arief-hidayat** [comment]
My bad. 
I revise my statement
* I can find `INFO (shrpx_worker.cc:525) Perform mapping selection` in the pod log. It's buried by other logs.
* However, I still couldn't find it in the kibana. I can see other shrpx_worker.cc INFO log in kibana , e.g.
 `INFO (shrpx_worker.cc:371) [WORKER:0x7f7149557000] WorkerEvent: client_fd=32, addrlen=16`

Perhaps it's kibana issue.

So, how to make this log available in both stderr and file?
At least I can grep it from file. Thanks again

**Comment by tatsuhiro-t** [comment]
Either stderr, or file.   You can change the location of log file using errorlog-file option.  https://github.com/zlabjp/nghttpx-ingress-lb#logs

**Comment by arief-hidayat** [comment]
i see. thank you for your help
