### ISSUE TITLE
support protocol H1 and H2

### ISSUE THREAD

**Issue by arief-hidayat** [zlabjp/nghttpx-ingress-lb#84]
Hi,

I'm trying to serve both grpc and http for same service same port (443).
Basically the backend service will do the following:
* if the request is grpc, it will pass thru to the grpc server (same pod, different container)
* if the request is http, it will convert the http request to grpc request and send to that grpc server.

If I set proto to H2. grpc request is fine but request for http 1.1 failed 
```
assert response.successful
       |        |
       |        false
       Response{protocol=http/1.1, code=502, message=Bad Gateway, url=....
```

If I set proto to http 1.1, http request is fine but grpc request failed 

```
main] ERROR com.sap.mlf.tfs.TfsJavaClient - request RPC failed: {0}
io.grpc.StatusRuntimeException: UNIMPLEMENTED: HTTP status code 404
invalid content-type: text/plain; charset=utf-8
headers: Metadata(:status=404,content-type=text/plain; charset=utf-8,x-content-type-options=nosniff,date=Tue, 03 Jul 2018 16:09:07 GMT,content-length=10,server=nghttpx,via=1.1 nghttpx)
DATA-----------------------------
Not Found
```

Is there a way to make it work for both H1 and H2?

thanks

**Comment by tatsuhiro-t** [comment]
It is possible to covert h1 to h2, but converting from h1 to gGRPC is generally not possible with nghttpx.
gRPC might require its own header fields or semantics, and nghttpx does not know that.

**Comment by arief-hidayat** [comment]
the convertion from h1 to grpc is done by my backing service. I don't expect it to be handled by nghttpx or ingress controller.

it's just that I want to merge these two different svc & port 
```
ingress.zlab.co.jp/backend-config:  {"devg-ecdd1595-48ac-4449-bdc1-190d37f99fd4": {"8000": {"proto": "h2"}, "9000": {"proto": "http/1.1"}}}
```
into one
```
ingress.zlab.co.jp/backend-config:  {"devg-ecdd1595-48ac-4449-bdc1-190d37f99fd4": {"8000": {"proto": "h2-and-http/1.1"}}}
```

is it possible?

**Comment by tatsuhiro-t** [comment]
Ah, sorry I misunderstood that.

So nghttpx should do on the same frontend port:

- if incoming request is h1, pass it to backend in h1.
- if incoming request is h2, pass it to backend in h2.

Choosing backend protocol depending on the frontend protocol is not possible at the moment.
You can mix multiple protocols in backend, but they are chosen in round robin manner.

I'm not sure how h1 request looks like, but if the backend can distinguish the normal HTTP request from gRPC request, then how about just sending all requests to backend in h2, and let backend decide whether the request is genuine gRPC or just h2 converted from h1.

**Comment by arief-hidayat** [comment]
Hi, 
I think I manage to work around this for my use case because I can differentiate the url path for grpc & http
Thanks. I'll close this
